name: deploy

on:
  workflow_run:
    workflows: ["build"]
    branches: [dev]
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: s0/git-publish-subdir-action@develop
        env:
          FOLDER: searx-heroku-main
          REPO: self
          BRANCH: main
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}    
 
  on-success2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: s0/git-publish-subdir-action@develop
        env:
          FOLDER: searx-heroku-searxng
          REPO: self
          BRANCH: searxng
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}              
